[phases.setup]
nixPkgs = ["nodejs", "python3", "python3Packages.pip"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "npm install",
  "npm run build"
]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "npm start" 