[phases.setup]
nixPkgs = [
  "nodejs",
  "python3",
  "python3Packages.pip",
  "python3Packages.setuptools",
  "python3Packages.wheel",
  "python3Packages.numpy",
  "python3Packages.pillow",
  "python3Packages.opencv4",
  "pkg-config",
  "cmake",
  "gcc",
  "libGL",
  "libGLU",
  "xorg.libX11",
  "xorg.libXext",
  "xorg.libXrender"
]

[phases.install]
cmds = [
  "npm install",
  "npm run build"
]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "npm start"

[variables]
PYTHONPATH = "/nix/store/*/lib/python3.12/site-packages"