[phases.setup]
nixPkgs = [
  "nodejs",
  "python3",
  "python3Packages.pip",
  "python3Packages.numpy",
  "python3Packages.pillow",
  "pkg-config",
  "cmake",
  "gcc",
  "libGL",
  "libGLU",
  "xorg.libX11",
  "xorg.libXext",
  "xorg.libXrender"
]

[phases.install]
cmds = [
  "python3 -m pip install --user opencv-python-headless",
  "python3 -c 'import cv2; print(\"OpenCV version:\", cv2.__version__)'",
  "npm install",
  "npm run build"
]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "npm start"

[variables]
PYTHONPATH = "/root/.local/lib/python3.12/site-packages:/nix/store/*/lib/python3.12/site-packages"
OPENCV_HEADLESS = "1" 