[phases.setup]
nixPkgs = [
  "nodejs",
  "python3",
  "python3Packages.pip",
  "python3Packages.setuptools",
  "python3Packages.wheel",
  "python3Packages.numpy",
  "python3Packages.pillow",
  "pkg-config",
  "cmake",
  "gcc",
  "libGL",
  "libGLU",
  "xorg.libX11",
  "xorg.libXext",
  "xorg.libXrender"
]

[phases.install]
cmds = [
  "curl -sS https://bootstrap.pypa.io/get-pip.py -o get-pip.py",
  "python3 get-pip.py --user",
  "$HOME/.local/bin/pip install --user opencv-python-headless",
  "npm install",
  "npm run build"
]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "npm start"

[variables]
PYTHONPATH = "/root/.local/lib/python3.12/site-packages:/nix/store/*/lib/python3.12/site-packages"
OPENCV_HEADLESS = "1" 