[phases.setup]
nixPkgs = [
  "nodejs", 
  "python3", 
  "python3Packages.pip",
  "python3Packages.opencv4",
  "python3Packages.numpy", 
  "python3Packages.pillow"
]

[phases.install]
cmds = [
  "npm install",
  "npm run build"
]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "npm start" 